using AerodynamicObjects.Aerodynamics;
using UnityEngine;

namespace AerodynamicObjects
{
    /// <summary>
    /// Creates an arrow with scale and direction proportional to the buoyancy force generated by an AeroObject's Buoyancy Model.
    /// </summary>
    [AddComponentMenu("Aerodynamic Objects/Visualisation/Buoyancy Arrow")]
    public class BuoyancyArrow : ArrowComponent
    {
        AeroObject aeroObject;
        BuoyancyModel model;
        int modelIndex;
        Arrow arrow;
        public Color colour = new Color(0.15f, 0.15f, 0.15f, 0.5f);

        private void OnEnable()
        {
            aeroObject = TryGetAeroObject();
            model = aeroObject.GetModel<BuoyancyModel>();

            if (model == null)
            {
                Debug.LogWarning("No buoyancy model was found for the buoyancy arrow component on " + name + ". Destroying the buoyancy arrow component.");
                Destroy(this);
                return;
            }

            modelIndex = aeroObject.GetModelIndex<BuoyancyModel>();
            arrow = new Arrow(colour, "Buoyancy Arrow");
        }

        void Update()
        {
            if (UseCoefficientForScale)
            {
                SetArrowPositionAndRotationFromVector(arrow, Physics.gravity.normalized, aeroObject.transform.position);
            }
            else
            {
                SetArrowPositionAndRotationFromVector(arrow, aeroObject.transform.TransformDirection(aeroObject.aerodynamicLoads[modelIndex].force), aeroObject.transform.position);
            }
        }

        public override void CleanUp()
        {
            arrow?.DestroyArrow();
        }
    }
}
